# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"1\n\x0c\x43heckRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"B\n\rCheckResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2W\n\x10InventoryService\x12\x43\n\x0e\x43heckInventory\x12\x17.inventory.CheckRequest\x1a\x18.inventory.CheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKREQUEST']._serialized_start=30
  _globals['_CHECKREQUEST']._serialized_end=79
  _globals['_CHECKRESPONSE']._serialized_start=81
  _globals['_CHECKRESPONSE']._serialized_end=147
  _globals['_INVENTORYSERVICE']._serialized_start=149
  _globals['_INVENTORYSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
