# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub:
    """Order service contract: place an order. The order service itself calls
    the inventory service (inventory.proto) with a 2.0s deadline and maps the
    outcome onto gRPC statuses, mirroring the REST order service:

    bad quantity (<= 0)               -> INVALID_ARGUMENT
    inventory NOT_FOUND               -> NOT_FOUND
    inventory FAILED_PRECONDITION     -> FAILED_PRECONDITION
    inventory too slow (2.0s deadline)-> DEADLINE_EXCEEDED
    otherwise                         -> PlaceOrderResponse(status="confirmed")
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/orders.OrderService/PlaceOrder',
                request_serializer=order__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=order__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)


class OrderServiceServicer:
    """Order service contract: place an order. The order service itself calls
    the inventory service (inventory.proto) with a 2.0s deadline and maps the
    outcome onto gRPC statuses, mirroring the REST order service:

    bad quantity (<= 0)               -> INVALID_ARGUMENT
    inventory NOT_FOUND               -> NOT_FOUND
    inventory FAILED_PRECONDITION     -> FAILED_PRECONDITION
    inventory too slow (2.0s deadline)-> DEADLINE_EXCEEDED
    otherwise                         -> PlaceOrderResponse(status="confirmed")
    """

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=order__pb2.PlaceOrderRequest.FromString,
                    response_serializer=order__pb2.PlaceOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orders.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService:
    """Order service contract: place an order. The order service itself calls
    the inventory service (inventory.proto) with a 2.0s deadline and maps the
    outcome onto gRPC statuses, mirroring the REST order service:

    bad quantity (<= 0)               -> INVALID_ARGUMENT
    inventory NOT_FOUND               -> NOT_FOUND
    inventory FAILED_PRECONDITION     -> FAILED_PRECONDITION
    inventory too slow (2.0s deadline)-> DEADLINE_EXCEEDED
    otherwise                         -> PlaceOrderResponse(status="confirmed")
    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrderService/PlaceOrder',
            order__pb2.PlaceOrderRequest.SerializeToString,
            order__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
