# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x06orders\"6\n\x11PlaceOrderRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"G\n\x12PlaceOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x32S\n\x0cOrderService\x12\x43\n\nPlaceOrder\x12\x19.orders.PlaceOrderRequest\x1a\x1a.orders.PlaceOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLACEORDERREQUEST']._serialized_start=23
  _globals['_PLACEORDERREQUEST']._serialized_end=77
  _globals['_PLACEORDERRESPONSE']._serialized_start=79
  _globals['_PLACEORDERRESPONSE']._serialized_end=150
  _globals['_ORDERSERVICE']._serialized_start=152
  _globals['_ORDERSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
